package clfirewall

var botUserAgents = []string{
	// Scanners de vulnérabilités / Outils d'attaque
	"masscan",
	"nmap",
	"nikto",
	"sqlmap",
	"havij",
	"acunetix",
	"nessus",
	"openvas",
	// Scrapers
	"scrapy",
	"mechanize",
	// Clients HTTP génériques (souvent scraping)
	"python-requests",
	"python-urllib",
	"go-http-client",
	"wget",
	"curl",
	"libwww-perl",
	"PHP",
	"java",
	"ruby",
	"httpx",
	"axios",
	// Bots SEO/commerciaux
	"ahrefsbot",
	"semrushbot",
	"dotbot",
	"mj12bot",
	"blexbot",
	"dataforseobot",
	"zoominfobot",
	"barkrowler",
}

// https://github.com/ai-robots-txt/ai.robots.txt
var iaBots = []string{
	"addsearchbot",
	"ai2bot",
	"ai2bot-deepresearcheval",
	"ai2bot-dolma",
	"aihitbot",
	"amazon-kendra",
	"amazonbot",
	"amazonbuyforme",
	"andibot",
	"anomura",
	"anthropic-ai",
	"applebot",
	"applebot-extended",
	"atlassian-bot",
	"awario",
	"bedrockbot",
	"bigsur.ai",
	"bravebot",
	"brightbot 1.0",
	"buddybot",
	"bytespider",
	"ccbot",
	"channel3bot",
	"chatglm-spider",
	"chatgpt agent",
	"chatgpt-user",
	"claude-searchbot",
	"claude-user",
	"claude-web",
	"claudebot",
	"cloudflare-autorag",
	"cloudvertexbot",
	"cohere-ai",
	"cohere-training-data-crawler",
	"cotoyogi",
	"crawl4ai",
	"crawlspace",
	"datenbank crawler",
	"deepseekbot",
	"devin",
	"diffbot",
	"duckassistbot",
	"echobot bot",
	"echoboxbot",
	"facebookbot",
	"facebookexternalhit",
	"factset_spyderbot",
	"firecrawlagent",
	"friendlycrawler",
	"gemini-deep-research",
	"google-cloudvertexbot",
	"google-extended",
	"google-firebase",
	"google-notebooklm",
	"googleagent-mariner",
	"googleother",
	"googleother-image",
	"googleother-video",
	"gptbot",
	"iaskbot",
	"iaskspider",
	"iaskspider/2.0",
	"iboubot",
	"icc-crawler",
	"imagesiftbot",
	"imagespider",
	"img2dataset",
	"isscyberriskcrawler",
	"kangaroo bot",
	"klaviyoaibot",
	"kunatocrawler",
	"laion-huggingface-processor",
	"laiondownloader",
	"lcc",
	"linerbot",
	"linguee bot",
	"linkupbot",
	"manus-user",
	"meta-externalagent",
	"meta-externalagent",
	"meta-externalfetcher",
	"meta-externalfetcher",
	"meta-webindexer",
	"mistralai-user",
	"mistralai-user/1.0",
	"mycentralscraperbot",
	"netestate imprint crawler",
	"notebooklm",
	"novaact",
	"oai-searchbot",
	"omgili",
	"omgilibot",
	"openai",
	"operator",
	"pangubot",
	"panscient",
	"panscient.com",
	"perplexity-user",
	"perplexitybot",
	"petalbot",
	"phindbot",
	"poggio-citations",
	"poseidon research crawler",
	"qualifiedbot",
	"quillbot",
	"quillbot.com",
	"sbintuitionsbot",
	"scrapy",
	"semrushbot-ocob",
	"semrushbot-swa",
	"shapbot",
	"sidetrade indexer bot",
	"spider",
	"terracotta",
	"thinkbot",
	"tiktokspider",
	"timpibot",
	"twinagent",
	"velenpublicwebcrawler",
	"wardbot",
	"webzio-extended",
	"wpbot",
	"wrtnbot",
	"yak",
	"yandexadditional",
	"yandexadditionalbot",
	"youbot",
	"zanistabot",
}

var legitimateBots = []string{
	// Moteurs de recherche majeurs
	"googlebot",
	"googlebot-image",
	"googlebot-video",
	"googlebot-news",
	"google-inspectiontool",
	"bingbot",
	"slurp", // Yahoo
	"duckduckbot",
	"applebot", // Siri/Spotlight
	"yeti",     // Naver (Corée)
	// Moteurs de recherche secondaires
	"yandexbot",   // Russie
	"baiduspider", // Chine
	"sogou",       // Chine
	"petalbot",    // Huawei
	"aspiegelbot", // Huawei Ask
	// Réseaux sociaux
	"facebookexternalhit",
	"facebookcatalog",
	"twitterbot",
	"linkedinbot",
	"whatsapp",
	"telegrambot",
	"discordbot",
	"slackbot",
	"pinterestbot",
	"redditbot",
	"quora link preview",
	// Monitoring et services
	"uptimerobot",
	"pingdom",
	"newrelic",
	"datadog",
	"site24x7",
	"statuscake",
	// Lecteurs RSS/Feed
	"feedly",
	"feedbin",
	"inoreader",
	"newsblur",
	// Autres services utiles
	"archive.org_bot", // Internet Archive
	"w3c_validator",
}
